export const generateRecap = (game, playerName) => {
    const { homeTeam, awayTeam, finalScore, stats, date, notes } = game;
    // const [homeScore, awayScore] = finalScore.split(' - ').map(Number); // Unused
    const isWin = game.outcome === 'Win';
    const isLoss = game.outcome === 'Loss';

    // --- 1. Header ---
    const dateObj = new Date(date);
    const dateStr = dateObj.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });

    let header = `🏀 GAME RECAP - ${dateStr}\n\n`;
    header += `${homeTeam} vs ${awayTeam}${notes ? ` - ${notes}` : ''}\n`;
    header += `Final Score: ${finalScore}\n\n`;

    // --- 2. Narrative Generation ---
    const pts = stats.points;
    const reb = stats.rebounds;
    const ast = stats.assists;
    const stl = stats.steals;
    const blk = stats.blocks;

    // Performance Descriptor
    let perfDesc = "steady effort";
    if (pts >= 20) perfDesc = "dominant performance";
    if (pts >= 30) perfDesc = "career-defining game";
    if (pts < 10) perfDesc = "quiet outing";

    // Shooting Descriptor
    const fgPct = stats.fga > 0 ? (stats.fgm / stats.fga) : 0;
    let shootingDesc = "getting involved early";
    if (fgPct > 0.5) shootingDesc = "shooting efficiently from the field";
    if (fgPct < 0.4 && stats.fga > 5) shootingDesc = "struggling to find rhythm offensively";

    // Outcome Descriptor
    let outcomeDesc = "contributing across multiple categories";
    if (isWin) outcomeDesc = "helping secure the team victory";
    if (isLoss) outcomeDesc = "fought hard in the loss";

    const narrative = `📊 ${playerName.toUpperCase()} PERFORMANCE BREAKDOWN\n\n`;
    const story = `${playerName} contributed ${pts} points in a ${perfDesc}, ${shootingDesc} and ${outcomeDesc}.\n\n`;

    // --- 3. Statistical Summary ---
    const fgCS = `${stats.fgm}/${stats.fga}`;
    const fgPctStr = stats.fga > 0 ? Math.round((stats.fgm / stats.fga) * 100) : 0;

    const tpCS = `${stats.fg3m}/${stats.fg3a}`;
    const ftCS = `${stats.ftm}/${stats.fta}`;

    let summary = `STATISTICAL SUMMARY:\n`;
    summary += `• Points: ${pts}\n`;
    summary += `• Field Goals: ${fgCS} (${fgPctStr}%)\n`;
    summary += `• 3-Pointers: ${tpCS}\n`;
    summary += `• Free Throws: ${ftCS}\n`;
    summary += `• Rebounds: ${reb}\n`;
    summary += `• Assists: ${ast}\n`;
    summary += `• Steals: ${stl}\n`;
    summary += `• Blocks: ${blk}\n`;
    summary += `• Turnovers: ${stats.turnovers}\n`;
    summary += `• Fouls: ${stats.fouls}\n`;
    summary += `• Minutes: 32\n`; // Placeholder as requested

    // --- 4. Shooting Breakdown ---
    const tpPct = stats.fg3a > 0 ? Math.round((stats.fg3m / stats.fg3a) * 100) : 0;
    const ftPct = stats.fta > 0 ? Math.round((stats.ftm / stats.fta) * 100) : 0;

    // 2-Point Calc
    const fg2m = stats.fgm - stats.fg3m;
    const fg2a = stats.fga - stats.fg3a;
    const fg2Pct = fg2a > 0 ? Math.round((fg2m / fg2a) * 100) : 0;

    let shooting = `\nSHOOTING BREAKDOWN:\n`;
    shooting += `• Overall FG%: ${fgPctStr}%\n`;
    shooting += `• 2-Point FG%: ${fg2Pct}%\n`;
    shooting += `• 3-Point FG%: ${tpPct}%\n`;
    shooting += `• Free Throw%: ${ftPct}%\n`;

    // --- 5. Period Breakdown ---
    let periods = `\nPERIOD-BY-PERIOD BREAKDOWN:\n`;
    // We currently only track Points per period
    Object.entries(stats.periodScores || {}).forEach(([period, score]) => {
        const pLabel = game.format === 'halves' ? `H${period}` : `Q${period}`;
        // Stubbing REB/AST as 0 since they aren't tracked per-period yet
        periods += `${pLabel}: ${score} PTS, 0 REB, 0 AST\n`;
    });

    const footer = `\n\nGenerated by Basketball Stats Tracker`;

    return header + narrative + story + summary + shooting + periods + footer;
};
